# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  node: circleci/node@4.6.0
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
jobs:
  build:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - node/install-npm:
          version: latest 
      - node/install-packages


workflows:
  Startup:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run